version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: batatabit-landing-page-mobile-first
    path: ""
    text-resources:
      - path: "*.html"
        format: html-hardcoded
